# Netlify configuration for InvestCloud Advisor Dashboard

[build]
  # Build command
  command = "npm run build"
  
  # Directory to deploy (Angular 17+ uses browser subdirectory)
  publish = "dist/investcloud-advisor/browser"

# SPA redirect rule - all routes redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    # Cache JavaScript files for 1 year (they have hashes)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    # Cache CSS files for 1 year (they have hashes)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache index.html
    Cache-Control = "public, max-age=0, must-revalidate"